# fly.toml app configuration file generated for fso-pokedex-cicd on 2026-05-11T15:59:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fso-pokedex-cicd'
primary_region = 'fra'

[build]

[env]
  PORT = 5001

[processes]
  app = "node app.js"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  timeout = "3s"
  path = "/health"
  success_threshold = 1
  failure_threshold = 3

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
