name: Hello World!

on:
  push:
    branches:
      - test-tags

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "$EVENT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit message
        env:
          COMMIT_MESSAGE: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGE"
      - name: only contains is true
        if: ${{ contains(github.event.commits.*.message, '#skip') }}
        run: echo "Ahoj svet"